package models

import (
	"time"

	"github.com/cannonball10/foundation/schemas/secrethitler"
	"github.com/cannonball10/foundation/utils"
)

// GameKeys provides key construction for the Game model.
// PK: GAME#{gameId}, SK: GAME#{gameId}
var GameKeys = NewKeyBuilder("GAME#", "GAME#")

// GameGSI1Keys provides key construction for the Game GSI1 (join-code lookup).
// GSI1PK: JOIN#{code}, GSI1SK: GAME#{gameId}
var GameGSI1Keys = NewKeyBuilder("JOIN#", "GAME#")

// GameGSI2Keys provides key construction for the Game GSI2 (host's games).
// GSI2PK: HOST#{userId}, GSI2SK: GAME#{gameId}
var GameGSI2Keys = NewKeyBuilder("HOST#", "GAME#")

// Game is a single Secret Hitler match. It owns all mutable state that
// drives the current turn; per-round records (governments, votes, actions,
// events) hang off the game via PK=GAME#{gameId}.
type Game struct {
	Timestamps

	GameID     string                  `json:"gameId"`
	JoinCode   string                  `json:"joinCode"`
	HostUserID string                  `json:"hostUserId"`
	Status     secrethitler.GameStatus `json:"status"`
	Phase      secrethitler.GamePhase  `json:"phase"`

	// Round is incremented each time a new president is seated.
	Round int `json:"round"`

	// Seating positions reference Player.Seat values (0-indexed).
	PresidentSeat          int  `json:"presidentSeat"`
	ChancellorSeat         *int `json:"chancellorSeat,omitempty"`
	PreviousPresidentSeat  *int `json:"previousPresidentSeat,omitempty"`
	PreviousChancellorSeat *int `json:"previousChancellorSeat,omitempty"`
	// SpecialElectionReturnSeat, when set, is the seat the presidency
	// returns to after a special-election-nominated president finishes.
	SpecialElectionReturnSeat *int `json:"specialElectionReturnSeat,omitempty"`

	// CurrentGovernmentID references the active Government (if any).
	CurrentGovernmentID string `json:"currentGovernmentId,omitempty"`

	// Policy counts enacted so far.
	LiberalPoliciesEnacted int `json:"liberalPoliciesEnacted"`
	FascistPoliciesEnacted int `json:"fascistPoliciesEnacted"`

	// Deck state tracked as remaining counts; a server-side shuffled
	// order is kept in DrawPile for deterministic draws.
	DrawPile    []secrethitler.PolicyType `json:"-"`
	DiscardPile []secrethitler.PolicyType `json:"-"`

	// ElectionTracker counts consecutive failed elections (0-2).
	ElectionTracker int `json:"electionTracker"`

	// VetoUnlocked becomes true once 5 fascist policies are enacted.
	VetoUnlocked bool `json:"vetoUnlocked"`

	// PlayerCount is captured when the game starts so clients can show
	// the intended size while players are still joining the lobby.
	PlayerCount int `json:"playerCount"`

	// Winner and WinCondition are set when the game ends.
	Winner       secrethitler.Party        `json:"winner,omitempty"`
	WinCondition secrethitler.WinCondition `json:"winCondition,omitempty"`

	// Lifecycle timestamps.
	StartedAt *time.Time `json:"startedAt,omitempty"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
}

// NewGame creates a new Game in the lobby state. If id is empty a ULID is
// generated. joinCode should be generated by the caller so the collision
// check against existing games can be performed with a conditional write.
func NewGame(id *string, joinCode, hostUserID string) *Game {
	if id == nil || *id == "" {
		ulid := utils.GenerateULID()
		id = &ulid
	}

	return &Game{
		Timestamps: NewTimestamps(),
		GameID:     *id,
		JoinCode:   joinCode,
		HostUserID: hostUserID,
		Status:     secrethitler.GameStatusLobby,
		Phase:      secrethitler.PhaseLobby,
	}
}

func (g *Game) PK() string { return GameKeys.PK(g.GameID) }
func (g *Game) SK() string { return GameKeys.SK(g.GameID) }

func (g *Game) GSIs() map[int]GSIKeyPair {
	return map[int]GSIKeyPair{
		1: GameGSI1Keys.Pair(g.JoinCode, g.GameID),
		2: GameGSI2Keys.Pair(g.HostUserID, g.GameID),
	}
}

// IsActive returns true when the game is in the lobby or in progress.
func (g *Game) IsActive() bool {
	return g.Status == secrethitler.GameStatusLobby ||
		g.Status == secrethitler.GameStatusInProgress
}

// HitlerZoneActive indicates fascist policies have reached the threshold
// where electing Hitler as Chancellor wins the game for the fascists.
func (g *Game) HitlerZoneActive() bool {
	return g.FascistPoliciesEnacted >= secrethitler.HitlerChancellorThreshold
}

func init() {
	RegisterModel(GameKeys, func() Model { return &Game{} })
}
